// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyBk9tnC8p3qIHfZcnt6BlagURlm23ak',
    appId: '1:1004319242831:web:3cda35bf75a913a04ac83a',
    messagingSenderId: '1004319242831',
    projectId: 'intramedia-a88af',
    authDomain: 'intramedia-a88af.firebaseapp.com',
    storageBucket: 'intramedia-a88af.appspot.com',
    measurementId: 'G-QFBLLXBSW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ts4aS6R3viFnO_NC58A9j_JtFqd1aDM',
    appId: '1:1004319242831:android:1d31cb39d5ceed9e4ac83a',
    messagingSenderId: '1004319242831',
    projectId: 'intramedia-a88af',
    storageBucket: 'intramedia-a88af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjEthtsWNdVldlMRQ5fG1MQrfMM2FM-o',
    appId: '1:1004319242831:ios:fe520c522bc04bb34ac83a',
    messagingSenderId: '1004319242831',
    projectId: 'intramedia-a88af',
    storageBucket: 'intramedia-a88af.appspot.com',
    iosBundleId: 'com.example.intraMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjEthtsWNdVldlMRQ5fG1MQrfMM2FM-o',
    appId: '1:1004319242831:ios:fe520c522bc04bb34ac83a',
    messagingSenderId: '1004319242831',
    projectId: 'intramedia-a88af',
    storageBucket: 'intramedia-a88af.appspot.com',
    iosBundleId: 'com.example.intraMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByyBk9tnC8p3qIHfZcnt6BlagURlm23ak',
    appId: '1:1004319242831:web:6e02c84ad834c22c4ac83a',
    messagingSenderId: '1004319242831',
    projectId: 'intramedia-a88af',
    authDomain: 'intramedia-a88af.firebaseapp.com',
    storageBucket: 'intramedia-a88af.appspot.com',
    measurementId: 'G-37H3C3X4DG',
  );
}
